import {
  ImgFatherDay1,
  ImgFatherDay10,
  ImgFatherDay2,
  ImgFatherDay3,
  ImgFatherDay4,
  ImgFatherDay5,
  ImgFatherDay6,
  ImgFatherDay7,
  ImgFatherDay8,
  ImgFatherDay9,
  ImgMotherDay1,
  ImgMotherDay2,
  ImgMotherDay3,
  ImgMotherDay4,
  ImgSocios1,
  ImgSocios2,
  ImgSocios3,
  ImgSocios4,
  ImgSocios5,
  ImgSocios6,
  ImgSocios7,
  ImgSocios8,
  ImgSocios9,
  ImgSocios10,
} from "../images";

export const flipBookList = [
  {
    type: "motherDay",
    images: [ImgMotherDay1, ImgMotherDay2, ImgMotherDay3, ImgMotherDay4],
  },
  {
    type: "fatherDay",
    images: [
      ImgFatherDay1,
      ImgFatherDay2,
      ImgFatherDay3,
      ImgFatherDay4,
      ImgFatherDay5,
      ImgFatherDay6,
      ImgFatherDay7,
      ImgFatherDay8,
      ImgFatherDay9,
      ImgFatherDay10,
    ],
  },
  {
    type: "eventDeportivo",
    images: [
        ImgSocios1,
      ImgSocios2,
      ImgSocios3,
      ImgSocios4,
      ImgSocios5,
      ImgSocios6,
      ImgSocios7,
      ImgSocios8,
      ImgSocios9,
      ImgSocios10,

    ],
  },
];
