import {
  ImgFatherDay1,
  ImgFatherDay10,
  ImgFatherDay2,
  ImgFatherDay3,
  ImgFatherDay4,
  ImgFatherDay5,
  ImgFatherDay6,
  ImgFatherDay7,
  ImgFatherDay8,
  ImgFatherDay9,
  ImgMotherDay1,
  ImgMotherDay2,
  ImgMotherDay3,
  ImgMotherDay4,
  ImgSocios1,
  ImgSocios2,
  ImgSocios3,
  ImgSocios4,
  ImgSocios5,
  ImgSocios6,
  ImgSocios7,
  ImgSocios8,
  ImgSocios9,
  ImgSocios10,
  ImgImposicion1,
  ImgImposicion2,
  ImgImposicion3,
  ImgImposicion4,
  ImgImposicion5,
  ImgImposicion6,
  ImgImposicion7,
  ImgImposicion8,
  almuerzo1,
  almuerzo2,
  almuerzo3,
  almuerzo4,
  almuerzo5,
  almuerzo6,
  almuerzo7,
  almuerzo8,
  almuerzo9,
  almuerzo10,
  almuerzo11,
  almuerzo12,
  almuerzo13,
  almuerzo14,
  ImgCallGeneralMeeting2,
  ImgCallGeneralMeeting1,
  ImgSwearingBoardDirectorsAfSurvelillance2,
  ImgSwearingBoardDirectorsAfSurvelillance1,
  ImgGalaDinnerStsStaffDay1,
  ImgLaborDay1,
  ImgPersonnelTraining1,
  ImgInterpromotionsOpeningChampionship1,
  ImgInterpromotionsOpeningChampionship2,
  ImgWorks1,
  ImgWorks2,
} from "../images";

export const flipBookList = [
  {
    type: "motherDay",
    images: [ImgMotherDay1, ImgMotherDay2, ImgMotherDay3, ImgMotherDay4],
  },
  {
    type: "fatherDay",
    images: [
      ImgFatherDay1,
      ImgFatherDay2,
      ImgFatherDay3,
      ImgFatherDay4,
      ImgFatherDay5,
      ImgFatherDay6,
      ImgFatherDay7,
      ImgFatherDay8,
      ImgFatherDay9,
      ImgFatherDay10,
    ],
  },

  {
    type: "eventDeportivo",
    images: [
      ImgSocios1,
      ImgSocios2,
      ImgSocios3,
      ImgSocios4,
      ImgSocios5,
      ImgSocios6,
      ImgSocios7,
      ImgSocios8,
      ImgSocios9,
      ImgSocios10,
    ],
  },
  {
    type: "imposicionMedalla",
    images: [
      ImgImposicion1,
      ImgImposicion2,
      ImgImposicion3,
      ImgImposicion4,
      ImgImposicion5,
      ImgImposicion6,
      ImgImposicion7,
      ImgImposicion8,
    ],
  },
  {
    type: "NationalHolidays",
    images: [
      almuerzo1,
      almuerzo2,
      almuerzo3,
      almuerzo4,
      almuerzo5,
      almuerzo6,
      almuerzo7,
      almuerzo8,
      almuerzo9,
      almuerzo10,
      almuerzo11,
      almuerzo12,
      almuerzo13,
      almuerzo14,
    ],
  },
  {
    type: "callGeneralmeeting",
    images: [ImgCallGeneralMeeting1, ImgCallGeneralMeeting2],
  },
  {
    type: "swearingBoardDirectorsAfSurvelillance",
    images: [
      ImgSwearingBoardDirectorsAfSurvelillance1,
      ImgSwearingBoardDirectorsAfSurvelillance2,
    ],
  },
  {
    type: "laborDay",
    images: [ImgLaborDay1],
  },
  {
    type: "personnel-training",
    images: [ImgPersonnelTraining1],
  },
  {
    type: "interpromotions-opening-championship",
    images: [
      ImgInterpromotionsOpeningChampionship1,
      ImgInterpromotionsOpeningChampionship2,
    ],
  },
  {
    type: "works",
    images: [ImgWorks1, ImgWorks2],
  },
  {
    type: "galaDinnerStsStaffDay1",
    images: [ImgGalaDinnerStsStaffDay1],
  },
];
